export enum GMAIL_REDUCER_TYPE {
  SET_MESSAGES_ID,
  SET_MESSAGES_CONTENT,
  SET_MESSAGES,
  SET_CURRENT_LABEL,
  SET_LABELS,
  SET_CONTACTS,
  SET_SELECT,
  SET_CURRENT_CONTACT,
  SET_MESSAGE_MODEL_SHOW,
  SET_USER_EMAIL,
  SET_EDITOR_TYPE,
  SET_MESSAGE_THREAD,
}
